export const languages = {
  en: {
    code: "en",
    name: "English",
    translations: {
      // Navigation
      dashboard: "Dashboard",
      animals: "Animals",
      healthRecords: "Health Records",
      vaccinations: "Vaccinations",
      breeding: "Breeding",
      maintenance: "Maintenance",
      incidents: "Incidents",
      marketplace: "Marketplace",
      users: "Users",
      alerts: "Alerts",
      settings: "Settings",
      logout: "Logout",

      // Dashboard
      welcomeBack: "Welcome back",
      totalAnimals: "Total Animals",
      breedingSuccessRate: "Breeding Success Rate",
      healthIncidents: "Health Incidents",
      activeUsers: "Active Users",
      thisMonth: "this month",
      fromLastQuarter: "from last quarter",
      fromLastMonth: "from last month",
      thisWeek: "this week",
      exportReport: "Export Report",
      addAnimal: "Add Animal",
      populationByBreed: "Population by Breed",
      distributionByBreed: "Distribution of animals by breed type",
      recentActivities: "Recent Activities",
      latestFarmActivities: "Latest farm activities and updates",
      aiRecommendations: "AI Recommendations",
      suggestedActions: "Suggested actions based on your farm data",

      // Animals
      animalManagement: "Animal Management",
      manageLivestockRecords: "Manage your livestock records",
      exportCSV: "Export CSV",
      importCSV: "Import CSV",
      animalRecords: "Animal Records",
      completeListAnimals: "Complete list of all animals with filtering and search capabilities",
      searchByTagOrBreed: "Search by Tag ID or Breed...",
      filterByBreed: "Filter by Breed",
      filterByGender: "Filter by Gender",
      allBreeds: "All Breeds",
      allGenders: "All Genders",
      male: "Male",
      female: "Female",
      tagId: "Tag ID",
      breed: "Breed",
      gender: "Gender",
      dob: "DOB",
      weight: "Weight (kg)",
      condition: "Condition",
      status: "Status",
      location: "Location",
      actions: "Actions",
      showing: "Showing",
      to: "to",
      of: "of",
      results: "results",
      previous: "Previous",
      next: "Next",

      // Add Animal Form
      addNewAnimal: "Add New Animal",
      createNewAnimalRecord: "Create a new animal record",
      backToAnimals: "Back to Animals",
      animalInformation: "Animal Information",
      fillRequiredInformation: "Fill in all the required information for the new animal",
      basicInformation: "Basic Information",
      additionalInformation: "Additional Information",
      origin: "Origin",
      acquisitionType: "Acquisition Type",
      acquisitionDate: "Acquisition Date",
      sireId: "Sire ID",
      damId: "Dam ID",
      photo: "Photo",
      notes: "Notes",
      cancel: "Cancel",
      createAnimal: "Create Animal",
      creating: "Creating...",

      // Auth
      welcomeBackAuth: "Welcome Back",
      signInToAccount: "Sign in to your Farm Home account",
      loginMethod: "Login Method",
      email: "Email",
      phone: "Phone",
      sms: "SMS",
      phoneNumber: "Phone Number",
      password: "Password",
      signingIn: "Signing in...",
      signIn: "Sign In",
      forgotPassword: "Forgot your password?",
      dontHaveAccount: "Don't have an account?",
      signUp: "Sign up",

      // Language Selection
      selectLanguage: "Select Language",
      languageUpdated: "Language updated successfully",

      // Health Records
      healthRecordsDescription: "Track and manage animal health incidents and treatments",
      addHealthRecord: "Add Health Record",
      healthRecordInformation: "Health Record Information",
      animalTagId: "Animal Tag ID",
      healthIssue: "Health Issue",
      symptoms: "Symptoms",
      diagnosis: "Diagnosis",
      treatment: "Treatment",
      veterinarian: "Veterinarian",
      treatmentDate: "Treatment Date",
      followUpDate: "Follow-up Date",
      severity: "Severity",
      cost: "Cost",
      resolved: "Resolved",
      pending: "Pending",
      critical: "Critical",
      moderate: "Moderate",
      mild: "Mild",

      // Vaccinations
      vaccinationsDescription: "Manage vaccination schedules and records",
      addVaccination: "Add Vaccination",
      vaccinationInformation: "Vaccination Information",
      vaccineName: "Vaccine Name",
      manufacturer: "Manufacturer",
      batchNumber: "Batch Number",
      expiryDate: "Expiry Date",
      administeredBy: "Administered By",
      nextDueDate: "Next Due Date",
      vaccinationType: "Vaccination Type",
      dosage: "Dosage",
      administrationRoute: "Administration Route",
      sideEffects: "Side Effects",

      // Breeding
      breedingDescription: "Track breeding activities and fertility records",
      addBreedingRecord: "Add Breeding Record",
      breedingInformation: "Breeding Information",
      sireTagId: "Sire Tag ID",
      damTagId: "Dam Tag ID",
      breedingDate: "Breeding Date",
      breedingMethod: "Breeding Method",
      expectedDelivery: "Expected Delivery Date",
      actualDelivery: "Actual Delivery Date",
      numberOfOffspring: "Number of Offspring",
      breedingNotes: "Breeding Notes",
      naturalMating: "Natural Mating",
      artificialInsemination: "Artificial Insemination",
      successful: "Successful",
      failed: "Failed",
      inProgress: "In Progress",

      // Maintenance
      maintenanceDescription: "Schedule and track routine maintenance activities",
      addMaintenanceRecord: "Add Maintenance Record",
      maintenanceInformation: "Maintenance Information",
      maintenanceType: "Maintenance Type",
      equipmentId: "Equipment ID",
      maintenanceDate: "Maintenance Date",
      performedBy: "Performed By",
      description: "Description",
      partsUsed: "Parts Used",
      laborHours: "Labor Hours",
      totalCost: "Total Cost",
      nextMaintenanceDate: "Next Maintenance Date",
      equipmentMaintenance: "Equipment Maintenance",
      facilityMaintenance: "Facility Maintenance",
      fencingRepair: "Fencing Repair",
      feedingSystemMaintenance: "Feeding System Maintenance",

      // Incidents
      incidentsDescription: "Record and track farm incidents and emergencies",
      addIncident: "Add Incident",
      incidentInformation: "Incident Information",
      incidentType: "Incident Type",
      incidentDate: "Incident Date",
      reportedBy: "Reported By",
      affectedAnimals: "Affected Animals",
      incidentDescription: "Incident Description",
      actionsTaken: "Actions Taken",
      preventiveMeasures: "Preventive Measures",
      incidentStatus: "Incident Status",
      injury: "Injury",
      illness: "Illness",
      equipment: "Equipment",
      security: "Security",
      weather: "Weather",
      other: "Other",

      // Common
      save: "Save",
      saving: "Saving...",
      edit: "Edit",
      delete: "Delete",
      view: "View",
      backTo: "Back to",
      required: "Required",
      optional: "Optional",
      selectOption: "Select an option",
      searchRecords: "Search records...",
      filterBy: "Filter by",
      sortBy: "Sort by",
      dateRange: "Date Range",
      allTypes: "All Types",
      allStatuses: "All Statuses",
      recordAdded: "Record added successfully",
      recordUpdated: "Record updated successfully",
      recordDeleted: "Record deleted successfully",

      // Milestone 2 - Analytics & Reporting
      analytics: "Analytics",
      reports: "Reports",
      notifications: "Notifications",
      mobileApp: "Mobile App",
      advancedSearch: "Advanced Search",
      realTimeData: "Real-time Data",
      dashboardAnalytics: "Dashboard Analytics",
      performanceMetrics: "Performance Metrics",
      trendAnalysis: "Trend Analysis",
      customReports: "Custom Reports",
      scheduledReports: "Scheduled Reports",
      reportTemplates: "Report Templates",
      dataVisualization: "Data Visualization",
      kpiDashboard: "KPI Dashboard",
      alertsManagement: "Alerts Management",
      notificationSettings: "Notification Settings",
      pushNotifications: "Push Notifications",
      emailAlerts: "Email Alerts",
      smsAlerts: "SMS Alerts",
      criticalAlerts: "Critical Alerts",
      systemNotifications: "System Notifications",
      userNotifications: "User Notifications",
      mobileOptimization: "Mobile Optimization",
      offlineMode: "Offline Mode",
      syncData: "Sync Data",
      fieldDataEntry: "Field Data Entry",
      qrCodeScanning: "QR Code Scanning",
      voiceInput: "Voice Input",
      photoCapture: "Photo Capture",
      gpsLocation: "GPS Location",
      weatherIntegration: "Weather Integration",
      marketPrices: "Market Prices",
      inventoryManagement: "Inventory Management",
      feedManagement: "Feed Management",
      medicineInventory: "Medicine Inventory",
      equipmentTracking: "Equipment Tracking",
      supplierManagement: "Supplier Management",
      purchaseOrders: "Purchase Orders",
      salesRecords: "Sales Records",
      financialReports: "Financial Reports",
      profitLossAnalysis: "Profit & Loss Analysis",
      cashFlowTracking: "Cash Flow Tracking",
      budgetPlanning: "Budget Planning",
      costAnalysis: "Cost Analysis",
      revenueTracking: "Revenue Tracking",
      expenseManagement: "Expense Management",
      taxReporting: "Tax Reporting",
      auditTrail: "Audit Trail",
      dataBackup: "Data Backup",
      dataRestore: "Data Restore",
      systemLogs: "System Logs",
      userActivity: "User Activity",
      securityLogs: "Security Logs",
      complianceReports: "Compliance Reports",
      regulatoryCompliance: "Regulatory Compliance",
      certificationTracking: "Certification Tracking",
      qualityAssurance: "Quality Assurance",
      traceabilityReports: "Traceability Reports",
      animalWelfare: "Animal Welfare",
      environmentalImpact: "Environmental Impact",
      sustainabilityMetrics: "Sustainability Metrics",
      carbonFootprint: "Carbon Footprint",
      waterUsage: "Water Usage",
      energyConsumption: "Energy Consumption",
      wasteManagement: "Waste Management",
      organicCertification: "Organic Certification",
      biosecurity: "Biosecurity",
      quarantineManagement: "Quarantine Management",
      diseaseOutbreakTracking: "Disease Outbreak Tracking",
      epidemiologyReports: "Epidemiology Reports",
      publicHealthReporting: "Public Health Reporting",
      veterinaryCompliance: "Veterinary Compliance",
      drugResidueTracking: "Drug Residue Tracking",
      withdrawalPeriods: "Withdrawal Periods",
      treatmentProtocols: "Treatment Protocols",
      emergencyProcedures: "Emergency Procedures",
      disasterPreparedness: "Disaster Preparedness",
      businessContinuity: "Business Continuity",
      riskAssessment: "Risk Assessment",
      insuranceClaims: "Insurance Claims",
      legalCompliance: "Legal Compliance",
      contractManagement: "Contract Management",
      laborManagement: "Labor Management",
      staffScheduling: "Staff Scheduling",
      payrollIntegration: "Payroll Integration",
      trainingRecords: "Training Records",
      certificationManagement: "Certification Management",
      performanceEvaluation: "Performance Evaluation",
      workforceAnalytics: "Workforce Analytics",
      productivityMetrics: "Productivity Metrics",
      timeTracking: "Time Tracking",
      taskManagement: "Task Management",
      workOrderManagement: "Work Order Management",
      maintenanceScheduling: "Maintenance Scheduling",
      preventiveMaintenance: "Preventive Maintenance",
      equipmentLifecycle: "Equipment Lifecycle",
      assetManagement: "Asset Management",
      depreciationTracking: "Depreciation Tracking",
      replacementPlanning: "Replacement Planning",
      vendorManagement: "Vendor Management",
      serviceContracts: "Service Contracts",
      warrantyTracking: "Warranty Tracking",
      qualityControl: "Quality Control",
      inspectionReports: "Inspection Reports",
      calibrationRecords: "Calibration Records",
      standardsCompliance: "Standards Compliance",
      processOptimization: "Process Optimization",
      efficiencyMetrics: "Efficiency Metrics",
      benchmarking: "Benchmarking",
      bestPractices: "Best Practices",
      knowledgeBase: "Knowledge Base",
      documentManagement: "Document Management",
      policyManagement: "Policy Management",
      procedureManagement: "Procedure Management",
      trainingMaterials: "Training Materials",
      operationalManuals: "Operational Manuals",
      safetyProtocols: "Safety Protocols",
      emergencyContacts: "Emergency Contacts",
      communicationTools: "Communication Tools",
      messagingSystem: "Messaging System",
      videoConferencing: "Video Conferencing",
      collaborationTools: "Collaboration Tools",
      projectManagement: "Project Management",
      milestoneTracking: "Milestone Tracking",
      resourceAllocation: "Resource Allocation",
      capacityPlanning: "Capacity Planning",
      demandForecasting: "Demand Forecasting",
      supplyChainManagement: "Supply Chain Management",
      logisticsManagement: "Logistics Management",
      transportationTracking: "Transportation Tracking",
      deliveryScheduling: "Delivery Scheduling",
      routeOptimization: "Route Optimization",
      fuelManagement: "Fuel Management",
      vehicleTracking: "Vehicle Tracking",
      maintenanceAlerts: "Maintenance Alerts",
      inspectionSchedules: "Inspection Schedules",
      complianceChecks: "Compliance Checks",
      auditSchedules: "Audit Schedules",
      reviewCycles: "Review Cycles",
      approvalWorkflows: "Approval Workflows",
      documentApproval: "Document Approval",
      changeManagement: "Change Management",
      versionControl: "Version Control",
      accessControl: "Access Control",
      permissionManagement: "Permission Management",
      roleBasedAccess: "Role-based Access",
      multiFactorAuth: "Multi-factor Authentication",
      singleSignOn: "Single Sign-On",
      passwordPolicy: "Password Policy",
      sessionManagement: "Session Management",
      encryptionSettings: "Encryption Settings",
      dataPrivacy: "Data Privacy",
      gdprCompliance: "GDPR Compliance",
      dataRetention: "Data Retention",
      rightToErasure: "Right to Erasure",
      consentManagement: "Consent Management",
      privacySettings: "Privacy Settings",
      anonymization: "Anonymization",
      pseudonymization: "Pseudonymization",
      dataMinimization: "Data Minimization",
      purposeLimitation: "Purpose Limitation",
      storageOptimization: "Storage Optimization",
      archivalPolicies: "Archival Policies",
      deletionSchedules: "Deletion Schedules",
      retentionPolicies: "Retention Policies",
      backupStrategies: "Backup Strategies",
      recoveryProcedures: "Recovery Procedures",
      disasterRecovery: "Disaster Recovery",
      businessRecovery: "Business Recovery",
      systemResilience: "System Resilience",
      failoverMechanisms: "Failover Mechanisms",
      redundancyPlanning: "Redundancy Planning",
      loadBalancing: "Load Balancing",
      performanceMonitoring: "Performance Monitoring",
      systemHealth: "System Health",
      uptimeTracking: "Uptime Tracking",
      errorMonitoring: "Error Monitoring",
      debuggingTools: "Debugging Tools",
      troubleshooting: "Troubleshooting",
      supportTickets: "Support Tickets",
      helpDesk: "Help Desk",
      userSupport: "User Support",
      technicalSupport: "Technical Support",
      customerService: "Customer Service",
      feedbackManagement: "Feedback Management",
      suggestionBox: "Suggestion Box",
      featureRequests: "Feature Requests",
      bugReporting: "Bug Reporting",
      issueTracking: "Issue Tracking",
      resolutionTracking: "Resolution Tracking",
      escalationProcedures: "Escalation Procedures",
      serviceLevel: "Service Level",
      responseTime: "Response Time",
      resolutionTime: "Resolution Time",
      customerSatisfaction: "Customer Satisfaction",
      npsScore: "NPS Score",
      usabilityTesting: "Usability Testing",
      userExperience: "User Experience",
      interfaceDesign: "Interface Design",
      accessibilityCompliance: "Accessibility Compliance",
      mobileResponsiveness: "Mobile Responsiveness",
      crossPlatformCompatibility: "Cross-platform Compatibility",
      browserCompatibility: "Browser Compatibility",
      deviceCompatibility: "Device Compatibility",
      operatingSystemSupport: "Operating System Support",
      cloudIntegration: "Cloud Integration",
      apiIntegration: "API Integration",
      thirdPartyIntegrations: "Third-party Integrations",
      dataImportExport: "Data Import/Export",
      migrationTools: "Migration Tools",
      integrationTesting: "Integration Testing",
      systemTesting: "System Testing",
      userAcceptanceTesting: "User Acceptance Testing",
      performanceTesting: "Performance Testing",
      securityTesting: "Security Testing",
      penetrationTesting: "Penetration Testing",
      vulnerabilityAssessment: "Vulnerability Assessment",
      securityAudit: "Security Audit",
      complianceAudit: "Compliance Audit",
      internalAudit: "Internal Audit",
      externalAudit: "External Audit",
      auditReports: "Audit Reports",
      findingsManagement: "Findings Management",
      correctiveActions: "Corrective Actions",
      preventiveActions: "Preventive Actions",
      continuousImprovement: "Continuous Improvement",
      processImprovement: "Process Improvement",
      qualityImprovement: "Quality Improvement",
      operationalExcellence: "Operational Excellence",
      leanManagement: "Lean Management",
      sixSigma: "Six Sigma",
      kaizen: "Kaizen",
      innovationManagement: "Innovation Management",
      researchDevelopment: "Research & Development",
      technologyAdoption: "Technology Adoption",
      digitalTransformation: "Digital Transformation",
      automationOpportunities: "Automation Opportunities",
      aiIntegration: "AI Integration",
      machineLearning: "Machine Learning",
      predictiveAnalytics: "Predictive Analytics",
      dataScience: "Data Science",
      bigDataAnalytics: "Big Data Analytics",
      businessIntelligence: "Business Intelligence",
      dataWarehouse: "Data Warehouse",
      dataLake: "Data Lake",
      etlProcesses: "ETL Processes",
      dataGovernance: "Data Governance",
      dataQuality: "Data Quality",
      masterDataManagement: "Master Data Management",
      referenceData: "Reference Data",
      metadataManagement: "Metadata Management",
      dataLineage: "Data Lineage",
      dataCatalog: "Data Catalog",
      dataDiscovery: "Data Discovery",
      selfServiceAnalytics: "Self-service Analytics",
      adhocReporting: "Ad-hoc Reporting",
      executiveDashboards: "Executive Dashboards",
      operationalDashboards: "Operational Dashboards",
      tacticalDashboards: "Tactical Dashboards",
      strategicDashboards: "Strategic Dashboards",
      scorecards: "Scorecards",
      balancedScorecard: "Balanced Scorecard",
      kpiManagement: "KPI Management",
      metricDefinition: "Metric Definition",
      targetSetting: "Target Setting",
      thresholdManagement: "Threshold Management",
      alertConfiguration: "Alert Configuration",
      escalationRules: "Escalation Rules",
      notificationRules: "Notification Rules",
      workflowAutomation: "Workflow Automation",
      processAutomation: "Process Automation",
      roboticProcessAutomation: "Robotic Process Automation",
      intelligentAutomation: "Intelligent Automation",
      cognitiveAutomation: "Cognitive Automation",
      naturalLanguageProcessing: "Natural Language Processing",
      speechRecognition: "Speech Recognition",
      imageRecognition: "Image Recognition",
      computerVision: "Computer Vision",
      augmentedReality: "Augmented Reality",
      virtualReality: "Virtual Reality",
      mixedReality: "Mixed Reality",
      iotIntegration: "IoT Integration",
      sensorData: "Sensor Data",
      telemetryData: "Telemetry Data",
      realTimeMonitoring: "Real-time Monitoring",
      edgeComputing: "Edge Computing",
      cloudComputing: "Cloud Computing",
      hybridCloud: "Hybrid Cloud",
      multiCloud: "Multi-cloud",
      containerization: "Containerization",
      microservices: "Microservices",
      serverlessComputing: "Serverless Computing",
      devopsIntegration: "DevOps Integration",
      cicdPipelines: "CI/CD Pipelines",
      infrastructureAsCode: "Infrastructure as Code",
      configurationManagement: "Configuration Management",
      environmentManagement: "Environment Management",
      releaseManagement: "Release Management",
      deploymentAutomation: "Deployment Automation",
      rollbackProcedures: "Rollback Procedures",
      blueGreenDeployment: "Blue-Green Deployment",
      canaryDeployment: "Canary Deployment",
      featureFlags: "Feature Flags",
      abTesting: "A/B Testing",
      experimentationPlatform: "Experimentation Platform",
      userSegmentation: "User Segmentation",
      personalization: "Personalization",
      recommendationEngine: "Recommendation Engine",
      contentManagement: "Content Management",
      digitalAssetManagement: "Digital Asset Management",
      brandManagement: "Brand Management",
      marketingAutomation: "Marketing Automation",
      campaignManagement: "Campaign Management",
      leadManagement: "Lead Management",
      customerRelationshipManagement: "Customer Relationship Management",
      salesForceAutomation: "Sales Force Automation",
      opportunityManagement: "Opportunity Management",
      pipelineManagement: "Pipeline Management",
      forecastingAccuracy: "Forecasting Accuracy",
      salesAnalytics: "Sales Analytics",
      customerAnalytics: "Customer Analytics",
      marketAnalytics: "Market Analytics",
      competitiveAnalysis: "Competitive Analysis",
      swotAnalysis: "SWOT Analysis",
      pestAnalysis: "PEST Analysis",
      portersFiveForces: "Porter's Five Forces",
      valueChainAnalysis: "Value Chain Analysis",
      businessModelCanvas: "Business Model Canvas",
      strategicPlanning: "Strategic Planning",
      tacticalPlanning: "Tactical Planning",
      operationalPlanning: "Operational Planning",
      scenarioPlanning: "Scenario Planning",
      contingencyPlanning: "Contingency Planning",
      riskManagement: "Risk Management",
      riskAssessmentMatrix: "Risk Assessment Matrix",
      riskMitigation: "Risk Mitigation",
      riskMonitoring: "Risk Monitoring",
      riskReporting: "Risk Reporting",
      complianceManagement: "Compliance Management",
      regulatoryReporting: "Regulatory Reporting",
      governanceFramework: "Governance Framework",
      policyFramework: "Policy Framework",
      controlFramework: "Control Framework",
      internalControls: "Internal Controls",
      segregationOfDuties: "Segregation of Duties",
      authorizationMatrix: "Authorization Matrix",
      approvalLimits: "Approval Limits",
      delegationOfAuthority: "Delegation of Authority",
      conflictOfInterest: "Conflict of Interest",
      ethicsManagement: "Ethics Management",
      codeOfConduct: "Code of Conduct",
      whistleblowerProtection: "Whistleblower Protection",
      fraudDetection: "Fraud Detection",
      fraudPrevention: "Fraud Prevention",
      antiCorruption: "Anti-corruption",
      antiMoneyLaundering: "Anti-money Laundering",
      sanctionsCompliance: "Sanctions Compliance",
      exportControls: "Export Controls",
      importRegulations: "Import Regulations",
      customsCompliance: "Customs Compliance",
      tradeCompliance: "Trade Compliance",
      internationalRegulations: "International Regulations",
      localRegulations: "Local Regulations",
      industryStandards: "Industry Standards",
      certificationRequirements: "Certification Requirements",
      accreditationManagement: "Accreditation Management",
      standardsCompliance: "Standards Compliance",
      qualityManagementSystem: "Quality Management System",
      environmentalManagementSystem: "Environmental Management System",
      healthSafetyManagementSystem: "Health & Safety Management System",
      informationSecurityManagementSystem: "Information Security Management System",
      businessContinuityManagementSystem: "Business Continuity Management System",
      riskManagementSystem: "Risk Management System",
      complianceManagementSystem: "Compliance Management System",
      integratedManagementSystem: "Integrated Management System",
      managementSystemAudit: "Management System Audit",
      certificationAudit: "Certification Audit",
      surveillanceAudit: "Surveillance Audit",
      recertificationAudit: "Recertification Audit",
      nonConformityManagement: "Non-conformity Management",
      correctiveActionManagement: "Corrective Action Management",
      preventiveActionManagement: "Preventive Action Management",
      managementReview: "Management Review",
      executiveReview: "Executive Review",
      boardReporting: "Board Reporting",
      stakeholderReporting: "Stakeholder Reporting",
      investorRelations: "Investor Relations",
      publicRelations: "Public Relations",
      mediaRelations: "Media Relations",
      communityRelations: "Community Relations",
      governmentRelations: "Government Relations",
      regulatorRelations: "Regulator Relations",
      industryAssociations: "Industry Associations",
      professionalNetworks: "Professional Networks",
      partnershipManagement: "Partnership Management",
      allianceManagement: "Alliance Management",
      jointVentureManagement: "Joint Venture Management",
      mergerAcquisitionIntegration: "Merger & Acquisition Integration",
      divestitureManagement: "Divestiture Management",
      spinoffManagement: "Spinoff Management",
      corporateRestructuring: "Corporate Restructuring",
      organizationalDesign: "Organizational Design",
      changeManagementProgram: "Change Management Program",
      transformationProgram: "Transformation Program",
      culturalTransformation: "Cultural Transformation",
      leadershipDevelopment: "Leadership Development",
      talentManagement: "Talent Management",
      successionPlanning: "Succession Planning",
      careerDevelopment: "Career Development",
      skillsManagement: "Skills Management",
      competencyManagement: "Competency Management",
      learningManagement: "Learning Management",
      knowledgeManagement: "Knowledge Management",
      intellectualPropertyManagement: "Intellectual Property Management",
      patentManagement: "Patent Management",
      trademarkManagement: "Trademark Management",
      copyrightManagement: "Copyright Management",
      tradesecretManagement: "Trade Secret Management",
      licensingManagement: "Licensing Management",
      royaltyManagement: "Royalty Management",
      technologyTransfer: "Technology Transfer",
      innovationPortfolio: "Innovation Portfolio",
      rdPortfolio: "R&D Portfolio",
      productPortfolio: "Product Portfolio",
      servicePortfolio: "Service Portfolio",
      brandPortfolio: "Brand Portfolio",
      assetPortfolio: "Asset Portfolio",
      investmentPortfolio: "Investment Portfolio",
      portfolioOptimization: "Portfolio Optimization",
      capitalAllocation: "Capital Allocation",
      resourceOptimization: "Resource Optimization",
      costOptimization: "Cost Optimization",
      revenueOptimization: "Revenue Optimization",
      profitOptimization: "Profit Optimization",
      valueOptimization: "Value Optimization",
      performanceOptimization: "Performance Optimization",
      operationalOptimization: "Operational Optimization",
      strategicOptimization: "Strategic Optimization",
      tacticalOptimization: "Tactical Optimization",
      continuousOptimization: "Continuous Optimization",
    },
  },
  yo: {
    code: "yo",
    name: "Yoruba",
    translations: {
      dashboard: "Pẹpẹ Iṣakoso",
      animals: "Awọn Ẹranko",
      healthRecords: "Awọn Igbasilẹ Ilera",
      vaccinations: "Awọn Abẹrẹ",
      breeding: "Ibisi",
      maintenance: "Itọju",
      incidents: "Awọn Iṣẹlẹ",
      marketplace: "Ọja",
      users: "Awọn Olumulo",
      alerts: "Awọn Ikilọ",
      settings: "Awọn Eto",
      logout: "Jade",
      welcomeBack: "Kaabo pada",
      totalAnimals: "Lapapọ Awọn Ẹranko",
      animalManagement: "Iṣakoso Ẹranko",
      manageLivestockRecords: "Ṣakoso awọn igbasilẹ ẹranko rẹ",
      addNewAnimal: "Fi Ẹranko Tuntun Kun",
      signIn: "Wọle",
      email: "Imeeli",
      password: "Ọrọ Igbaniwọle",
      selectLanguage: "Yan Ede",
      languageUpdated: "Ede ti yipada ni aṣeyọri",

      // Health Records
      healthRecordsDescription: "Ṣe atẹle ati ṣakoso awọn iṣẹlẹ ilera ẹranko ati awọn itọju",
      addHealthRecord: "Fi Igbasilẹ Ilera Kun",
      healthRecordInformation: "Alaye Igbasilẹ Ilera",
      animalTagId: "ID Tag Ẹranko",
      healthIssue: "Ọran Ilera",
      symptoms: "Awọn aami aisan",
      diagnosis: "Ayẹwo",
      treatment: "Itọju",
      veterinarian: "Onisegun ẹranko",
      treatmentDate: "Ọjọ Itọju",
      followUpDate: "Ọjọ Tẹle-up",
      severity: "Buru to",
      cost: "Iye owo",
      resolved: "Ti pari",
      pending: "Ti nduro",
      critical: "Lekoko",
      moderate: "Iwọntunwọnsi",
      mild: "Rọrun",

      // Vaccinations
      vaccinationsDescription: "Ṣakoso awọn iṣeto ajesara ati awọn igbasilẹ",
      addVaccination: "Fi Ajesara Kun",
      vaccinationInformation: "Alaye Ajesara",
      vaccineName: "Orukọ Ajesara",
      manufacturer: "Olupese",
      batchNumber: "Nọmba ipele",
      expiryDate: "Ọjọ ipari",
      administeredBy: "Ti Ṣakoso Nipasẹ",
      nextDueDate: "Ọjọ Ti o tẹle",
      vaccinationType: "Iru Ajesara",
      dosage: "Iwọn lilo",
      administrationRoute: "Ọna Isakoso",
      sideEffects: "Awọn ipa ẹgbẹ",

      // Breeding
      breedingDescription: "Ṣe atẹle awọn iṣẹ ibisi ati awọn igbasilẹ irọyin",
      addBreedingRecord: "Ƙara Bayanin Kiwo",
      breedingInformation: "Alaye Ibisi",
      sireTagId: "ID Tag Baba",
      damTagId: "ID Tag Iya",
      breedingDate: "Ọjọ Ibisi",
      breedingMethod: "Ọna Ibisi",
      expectedDelivery: "Ọjọ Ifijiṣẹ Ti a Reti",
      actualDelivery: "Ọjọ Ifijiṣẹ Gangan",
      numberOfOffspring: "Nọmba Awọn Ọmọ",
      breedingNotes: "Awọn Akọsilẹ Ibisi",
      naturalMating: "Ibaṣepọ Adayeba",
      artificialInsemination: "Ifunni Artificial",
      successful: "Aṣeyọri",
      failed: "Kuna",
      inProgress: "Lọwọlọwọ",

      // Maintenance
      maintenanceDescription: "Ṣeto ati tọpa awọn iṣẹ itọju ṣiṣe",
      addMaintenanceRecord: "Fi Igbasilẹ Itọju Kun",
      maintenanceInformation: "Alaye Itọju",
      maintenanceType: "Iru Itọju",
      equipmentId: "ID Ohun elo",
      maintenanceDate: "Ọjọ Itọju",
      performedBy: "Ti Ṣe Nipasẹ",
      description: "Apejuwe",
      partsUsed: "Awọn Apakan Ti a Lo",
      laborHours: "Awọn Wakati Iṣẹ",
      totalCost: "Lapapọ Iye Owo",
      nextMaintenanceDate: "Ọjọ Itọju Ti o tẹle",
      equipmentMaintenance: "Itọju Ohun elo",
      facilityMaintenance: "Itọju Ohun elo",
      fencingRepair: "Atunṣe Ọgba",
      feedingSystemMaintenance: "Itọju Eto Ifunni",

      // Incidents
      incidentsDescription: "Gba silẹ ki o tọpa awọn iṣẹlẹ oko ati awọn pajawiri",
      addIncident: "Fi Iṣẹlẹ Kun",
      incidentInformation: "Alaye Iṣẹlẹ",
      incidentType: "Iru Iṣẹlẹ",
      incidentDate: "Ọjọ Iṣẹlẹ",
      reportedBy: "Ti royin Nipasẹ",
      affectedAnimals: "Awọn Ẹranko Ti o Kan",
      incidentDescription: "Apejuwe Iṣẹlẹ",
      actionsTaken: "Awọn Igbese Ti a Gbe",
      preventiveMeasures: "Awọn Iwọn Idaabobo",
      incidentStatus: "Ipo Iṣẹlẹ",
      injury: "Ipalara",
      illness: "Aisan",
      equipment: "Ohun elo",
      security: "Aabo",
      weather: "Oju ojo",
      other: "Omiiran",

      // Common
      save: "Fipamọ",
      saving: "N fi pamọ...",
      edit: "Ṣatunkọ",
      delete: "Paarẹ",
      view: "Wo",
      backTo: "Pada si",
      required: "Ti beere",
      optional: "Aṣayan",
      selectOption: "Yan aṣayan kan",
      searchRecords: "Wa awọn igbasilẹ...",
      filterBy: "Ṣe àlẹmọ nipasẹ",
      sortBy: "Ṣeto nipasẹ",
      dateRange: "Iwọn Ọjọ",
      allTypes: "Gbogbo Awọn Iru",
      allStatuses: "Gbogbo Awọn Ipo",
      recordAdded: "Igbasilẹ ti ṣafikun ni aṣeyọri",
      recordUpdated: "Igbasilẹ ti ni imudojuiwọn ni aṣeyọri",
      recordDeleted: "Igbasilẹ ti paarẹ ni aṣeyọri",
    },
  },
  ha: {
    code: "ha",
    name: "Hausa",
    translations: {
      dashboard: "Dashboard",
      animals: "Dabbobi",
      healthRecords: "Bayanan Lafiya",
      vaccinations: "Rigakafi",
      breeding: "Kiwo",
      maintenance: "Gyara",
      incidents: "Abubuwan da suka faru",
      marketplace: "Kasuwa",
      users: "Masu amfani",
      alerts: "Sanarwa",
      settings: "Saiti",
      logout: "Fita",
      welcomeBack: "Maraba da dawowa",
      totalAnimals: "Jimillar Dabbobi",
      animalManagement: "Sarrafa Dabbobi",
      manageLivestockRecords: "Sarrafa bayanan dabbobi",
      addNewAnimal: "Kara Sabon Dabba",
      signIn: "Shiga",
      email: "Imel",
      password: "Kalmar sirri",
      selectLanguage: "Zaɓi Harshe",
      languageUpdated: "An sabunta harshe cikin nasara",

      // Health Records
      healthRecordsDescription: "Bibiyar diddigan lafiyar dabbobi da jinyoyinsu",
      addHealthRecord: "Ƙara Bayanin Lafiya",
      healthRecordInformation: "Bayanin Bayanin Lafiya",
      animalTagId: "ID na Tag na Dabba",
      healthIssue: "Matsalar Lafiya",
      symptoms: "Alamomi",
      diagnosis: "Gano asali",
      treatment: "Jinya",
      veterinarian: "Likitan dabbobi",
      treatmentDate: "Ranar Jinya",
      followUpDate: "Ranar Bibiya",
      severity: "Tsanani",
      cost: "Kudin",
      resolved: "An warware",
      pending: "Ana jiran aiki",
      critical: "Mai tsanani",
      moderate: "Matsakaici",
      mild: "Mai sauƙi",

      // Vaccinations
      vaccinationsDescription: "Sarrafa jadawalin rigakafi da bayanan",
      addVaccination: "Ƙara Rigakafi",
      vaccinationInformation: "Bayanin Rigakafi",
      vaccineName: "Sunan Rigakafi",
      manufacturer: "Mai ƙira",
      batchNumber: "Lambar Batch",
      expiryDate: "Ranar karewa",
      administeredBy: "Wanda ya Gudanar",
      nextDueDate: "Ranar da za a biyo baya",
      vaccinationType: "Nau'in Rigakafi",
      dosage: "Adadin",
      administrationRoute: "Hanyar Gudanarwa",
      sideEffects: "Tasirin gefe",

      // Breeding
      breedingDescription: "Bibiyar ayyukan kiwo da bayanan haihuwa",
      addBreedingRecord: "Ƙara Bayanin Kiwo",
      breedingInformation: "Bayanin Kiwo",
      sireTagId: "ID na Tag na Uba",
      damTagId: "ID na Tag na Uwa",
      breedingDate: "Ranar Kiwo",
      breedingMethod: "Hanyar Kiwo",
      expectedDelivery: "Ranar Isarwa da ake Tsammani",
      actualDelivery: "Ranar Isarwa ta Gaskiya",
      numberOfOffspring: "Yawan 'Ya'ya",
      breedingNotes: "Bayanan Kiwo",
      naturalMating: "Jima'i na Halitta",
      artificialInsemination: "Shigar da Maniyi na Ƙirƙira",
      successful: "Mai nasara",
      failed: "Ya gaza",
      inProgress: "Ana ci gaba",

      // Maintenance
      maintenanceDescription: "Tsara da bibiyar ayyukan gyara na yau da kullun",
      addMaintenanceRecord: "Ƙara Bayanin Gyara",
      maintenanceInformation: "Bayanin Gyara",
      maintenanceType: "Nau'in Gyara",
      equipmentId: "ID na Kayan aiki",
      maintenanceDate: "Ranar Gyara",
      performedBy: "Wanda ya Yi",
      description: "Bayani",
      partsUsed: "Sassan da aka Yi Amfani da su",
      laborHours: "Awoyin Aiki",
      totalCost: "Jimillar Kuɗi",
      nextMaintenanceDate: "Ranar Gyara ta Gaba",
      equipmentMaintenance: "Gyaran Kayan aiki",
      facilityMaintenance: "Gyaran Wuri",
      fencingRepair: "Gyaran Shinge",
      feedingSystemMaintenance: "Gyaran Tsarin Ciyarwa",

      // Incidents
      incidentsDescription: "Rikodi da bibiyar abubuwan da suka faru a gona da gaggawa",
      addIncident: "Ƙara Abin da ya Faru",
      incidentInformation: "Bayanin Abin da ya Faru",
      incidentType: "Nau'in Abin da ya Faru",
      incidentDate: "Ranar Abin da ya Faru",
      reportedBy: "Wanda ya Ruwaito",
      affectedAnimals: "Dabbobin da abin ya shafa",
      incidentDescription: "Bayanin Abin da ya Faru",
      actionsTaken: "Matakan da aka ɗauka",
      preventiveMeasures: "Matakan Rigakafi",
      incidentStatus: "Matsayin Abin da ya Faru",
      injury: "Rauni",
      illness: "Rashin lafiya",
      equipment: "Kayan aiki",
      security: "Tsaro",
      weather: "Yanayi",
      other: "Sauran",

      // Common
      save: "Ajiye",
      saving: "Ana ajiyewa...",
      edit: "Gyara",
      delete: "Goge",
      view: "Duba",
      backTo: "Komawa",
      required: "Wajibi",
      optional: "Zaɓi",
      selectOption: "Zaɓi zaɓi",
      searchRecords: "Bincika bayanan...",
      filterBy: "Tace ta",
      sortBy: "Rarraba ta",
      dateRange: "Kewayon Kwanan Wata",
      allTypes: "Duk Nau'ikan",
      allStatuses: "Duk Matsayi",
      recordAdded: "An ƙara bayanin cikin nasara",
      recordUpdated: "An sabunta bayanin cikin nasara",
      recordDeleted: "An goge bayanin cikin nasara",
    },
  },
  lg: {
    code: "lg",
    name: "Igbo",
    translations: {
      dashboard: "Dashboard",
      animals: "Anụmanụ",
      healthRecords: "Ndekọ Ahụike",
      vaccinations: "Ọgwụ Mgbochi",
      breeding: "Ọmụmụ",
      maintenance: "Nlekọta",
      incidents: "Ihe Mere",
      marketplace: "Ahịa",
      users: "Ndị Ọrụ",
      alerts: "Ọkwa",
      settings: "Ntọala",
      logout: "Pụọ",
      welcomeBack: "Nnọọ ka ị laghachi",
      totalAnimals: "Ngụkọta Anụmanụ",
      animalManagement: "Njikwa Anụmanụ",
      manageLivestockRecords: "Jikwaa ndekọ anụmanụ gị",
      addNewAnimal: "Tinye Anụmanụ Ọhụrụ",
      signIn: "Banye",
      email: "Email",
      password: "Okwu nzuzo",
      selectLanguage: "Họrọ Asụsụ",
      languageUpdated: "Emelitela asụsụ nke ọma",

      // Health Records
      healthRecordsDescription: "Soro ma jikwaa ihe gbasara ahụike anụmanụ na ọgwụgwọ",
      addHealthRecord: "Tinye Ndekọ Ahụike",
      healthRecordInformation: "Ozi Ndekọ Ahụike",
      animalTagId: "ID Tag Anụmanụ",
      healthIssue: "Nsogbu Ahụike",
      symptoms: "Mgbaàmà",
      diagnosis: "Nchoputa",
      treatment: "Ọgwụgwọ",
      veterinarian: "Dọkịta anụmanụ",
      treatmentDate: "Ụbọchị Ọgwụgwọ",
      followUpDate: "Ụbọchị Nleba Anya",
      severity: "Oke",
      cost: "Ọnụ ahịa",
      resolved: "Edobere",
      pending: "Na-echere",
      critical: "Dị oke egwu",
      moderate: "Ọkara",
      mild: "Dị nro",

      // Vaccinations
      vaccinationsDescription: "Jikwaa usoro ịgba ọgwụ mgbochi ọrịa na ndekọ",
      addVaccination: "Tinye Ọgwụ Mgbochi Ọrịa",
      vaccinationInformation: "Ozi Ọgwụ Mgbochi Ọrịa",
      vaccineName: "Aha Ọgwụ Mgbochi Ọrịa",
      manufacturer: "Onye nrụpụta",
      batchNumber: "Nọmba Batch",
      expiryDate: "Ụbọchị ngafe",
      administeredBy: "Onye nyere ya",
      nextDueDate: "Ụbọchị Ọzọ",
      vaccinationType: "Ụdị Ọgwụ Mgbochi Ọrịa",
      dosage: "Ọnụọgụgụ",
      administrationRoute: "Ụzọ Nchịkwa",
      sideEffects: "Mmetụta Akụkụ",

      // Breeding
      breedingDescription: "Soro mmemme ọmụmụ na ndekọ ọmụmụ",
      addBreedingRecord: "Tinye Ndekọ Ọmụmụ",
      breedingInformation: "Ozi Ọmụmụ",
      sireTagId: "ID Tag Nna",
      damTagId: "ID Tag Nne",
      breedingDate: "Ụbọchị Ọmụmụ",
      breedingMethod: "Ụzọ Ọmụmụ",
      expectedDelivery: "Ụbọchị Nnyefe Atụrụ Anya",
      actualDelivery: "Ụbọchị Nnyefe Nke Eziokwu",
      numberOfOffspring: "Ọnụọgụgụ Ụmụaka",
      breedingNotes: "Ihe edeturu Ọmụmụ",
      naturalMating: "Ịlụ Di na Nwunye Ebumpụta Ụwa",
      artificialInsemination: "Mgbasa Ozi Artificial",
      successful: "Nke Ọma",
      failed: "Adaala",
      inProgress: "Na-aga n'ihu",

      // Maintenance
      maintenanceDescription: "Hazie ma soro mmemme ndozi oge niile",
      addMaintenanceRecord: "Tinye Ndekọ Ndozi",
      maintenanceInformation: "Ozi Ndozi",
      maintenanceType: "Ụdị Ndozi",
      equipmentId: "ID Akụrụngwa",
      maintenanceDate: "Ụbọchị Ndozi",
      performedBy: "Onye mere ya",
      description: "Nkọwa",
      partsUsed: "Akụkụ Ejiri",
      laborHours: "Awa Ọrụ",
      totalCost: "Ngụkọta Ọnụ Ahịa",
      nextMaintenanceDate: "Ụbọchị Ndozi Ọzọ",
      equipmentMaintenance: "Ndozi Akụrụngwa",
      facilityMaintenance: "Ndozi Ụlọ Ọrụ",
      fencingRepair: "Mmezi Ogige",
      feedingSystemMaintenance: "Ndozi Usoro Nri",

      // Incidents
      incidentsDescription: "Dekọọ ma soro ihe mere n'ugbo na ihe mberede",
      addIncident: "Tinye Ihe Mere",
      incidentInformation: "Ozi Ihe Mere",
      incidentType: "Ụdị Ihe Mere",
      incidentDate: "Ụbọchị Ihe Mere",
      reportedBy: "Onye kọrọ ya",
      affectedAnimals: "Anụmanụ Ndị Metụtara",
      incidentDescription: "Nkọwa Ihe Mere",
      actionsTaken: "Usoro Ndị E Mere",
      preventiveMeasures: "Usoro Mgbochi",
      incidentStatus: "Ọnọdụ Ihe Mere",
      injury: "Mmerụ ahụ",
      illness: "Ọrịa",
      equipment: "Akụrụngwa",
      security: "Nchekwa",
      weather: "Ihu igwe",
      other: "Ndị ọzọ",

      // Common
      save: "Chekwaa",
      saving: "Na-echekwa...",
      edit: "Dezie",
      delete: "Hichapụ",
      view: "Lee",
      backTo: "Laghachi na",
      required: "Achọrọ",
      optional: "Nhọrọ",
      selectOption: "Họrọ nhọrọ",
      searchRecords: "Chọọ ndekọ...",
      filterBy: "Jiri nzacha",
      sortBy: "Jiri ụdị",
      dateRange: "Usoro Ụbọchị",
      allTypes: "Ụdị Niile",
      allStatuses: "Ọnọdụ Niile",
      recordAdded: "E tinyela ndekọ nke ọma",
      recordUpdated: "Emeliteela ndekọ nke ọma",
      recordDeleted: "Ehichapụla ndekọ nke ọma",
    },
  },
  po: {
    code: "po",
    name: "Portuguese",
    translations: {
      dashboard: "Painel",
      animals: "Animais",
      healthRecords: "Registros de Saúde",
      vaccinations: "Vacinações",
      breeding: "Reprodução",
      maintenance: "Manutenção",
      incidents: "Incidentes",
      marketplace: "Mercado",
      users: "Usuários",
      alerts: "Alertas",
      settings: "Configurações",
      logout: "Sair",
      welcomeBack: "Bem-vindo de volta",
      totalAnimals: "Total de Animais",
      animalManagement: "Gestão de Animais",
      manageLivestockRecords: "Gerencie seus registros de gado",
      addNewAnimal: "Adicionar Novo Animal",
      signIn: "Entrar",
      email: "Email",
      password: "Senha",
      selectLanguage: "Selecionar Idioma",
      languageUpdated: "Idioma atualizado com sucesso",

      // Health Records
      healthRecordsDescription: "Acompanhe e gerencie incidentes e tratamentos de saúde animal",
      addHealthRecord: "Adicionar Registro de Saúde",
      healthRecordInformation: "Informações do Registro de Saúde",
      animalTagId: "ID da Etiqueta do Animal",
      healthIssue: "Problema de Saúde",
      symptoms: "Sintomas",
      diagnosis: "Diagnóstico",
      treatment: "Tratamento",
      veterinarian: "Veterinário",
      treatmentDate: "Data do Tratamento",
      followUpDate: "Data de Acompanhamento",
      severity: "Gravidade",
      cost: "Custo",
      resolved: "Resolvido",
      pending: "Pendente",
      critical: "Crítico",
      moderate: "Moderado",
      mild: "Leve",

      // Vaccinations
      vaccinationsDescription: "Gerenciar horários e registros de vacinação",
      addVaccination: "Adicionar Vacinação",
      vaccinationInformation: "Informações da Vacinação",
      vaccineName: "Nome da Vacina",
      manufacturer: "Fabricante",
      batchNumber: "Número do Lote",
      expiryDate: "Data de Validade",
      administeredBy: "Administrado Por",
      nextDueDate: "Próxima Data de Vencimento",
      vaccinationType: "Tipo de Vacinação",
      dosage: "Dosagem",
      administrationRoute: "Via de Administração",
      sideEffects: "Efeitos Colaterais",

      // Breeding
      breedingDescription: "Acompanhe as atividades de reprodução e os registros de fertilidade",
      addBreedingRecord: "Adicionar Registro de Reprodução",
      breedingInformation: "Informações de Reprodução",
      sireTagId: "ID da Etiqueta do Pai",
      damTagId: "ID da Etiqueta da Mãe",
      breedingDate: "Data de Reprodução",
      breedingMethod: "Método de Reprodução",
      expectedDelivery: "Data de Entrega Esperada",
      actualDelivery: "Data de Entrega Real",
      numberOfOffspring: "Número de Filhotes",
      breedingNotes: "Notas de Reprodução",
      naturalMating: "Acoplamento Natural",
      artificialInsemination: "Inseminação Artificial",
      successful: "Bem-sucedido",
      failed: "Falhou",
      inProgress: "Em Andamento",

      // Maintenance
      maintenanceDescription: "Agendar e acompanhar as atividades de manutenção de rotina",
      addMaintenanceRecord: "Adicionar Registro de Manutenção",
      maintenanceInformation: "Informações de Manutenção",
      maintenanceType: "Tipo de Manutenção",
      equipmentId: "ID do Equipamento",
      maintenanceDate: "Data de Manutenção",
      performedBy: "Realizado Por",
      description: "Descrição",
      partsUsed: "Peças Usadas",
      laborHours: "Horas de Trabalho",
      totalCost: "Custo Total",
      nextMaintenanceDate: "Próxima Data de Manutenção",
      equipmentMaintenance: "Manutenção de Equipamentos",
      facilityMaintenance: "Manutenção de Instalações",
      fencingRepair: "Reparo de Cercas",
      feedingSystemMaintenance: "Manutenção do Sistema de Alimentação",

      // Incidents
      incidentsDescription: "Registrar e acompanhar incidentes e emergências na fazenda",
      addIncident: "Adicionar Incidente",
      incidentInformation: "Informações do Incidente",
      incidentType: "Tipo de Incidente",
      incidentDate: "Data do Incidente",
      reportedBy: "Reportado Por",
      affectedAnimals: "Animais Afetados",
      incidentDescription: "Descrição do Incidente",
      actionsTaken: "Ações Tomadas",
      preventiveMeasures: "Medidas Preventivas",
      incidentStatus: "Status do Incidente",
      injury: "Lesão",
      illness: "Doença",
      equipment: "Equipamento",
      security: "Segurança",
      weather: "Clima",
      other: "Outro",

      // Common
      save: "Salvar",
      saving: "Salvando...",
      edit: "Editar",
      delete: "Excluir",
      view: "Visualizar",
      backTo: "Voltar para",
      required: "Obrigatório",
      optional: "Opcional",
      selectOption: "Selecione uma opção",
      searchRecords: "Pesquisar registros...",
      filterBy: "Filtrar por",
      sortBy: "Ordenar por",
      dateRange: "Intervalo de Datas",
      allTypes: "Todos os Tipos",
      allStatuses: "Todos os Status",
      recordAdded: "Registro adicionado com sucesso",
      recordUpdated: "Registro atualizado com sucesso",
      recordDeleted: "Registro excluído com sucesso",
    },
  },
  fr: {
    code: "fr",
    name: "French",
    translations: {
      dashboard: "Tableau de bord",
      animals: "Animaux",
      healthRecords: "Dossiers de santé",
      vaccinations: "Vaccinations",
      breeding: "Élevage",
      maintenance: "Maintenance",
      incidents: "Incidents",
      marketplace: "Marché",
      users: "Utilisateurs",
      alerts: "Alertes",
      settings: "Paramètres",
      logout: "Déconnexion",
      welcomeBack: "Bon retour",
      totalAnimals: "Total des animaux",
      animalManagement: "Gestion des animaux",
      manageLivestockRecords: "Gérez vos registres de bétail",
      addNewAnimal: "Ajouter un nouvel animal",
      signIn: "Se connecter",
      email: "Email",
      password: "Mot de passe",
      selectLanguage: "Sélectionner la langue",
      languageUpdated: "Langue mise à jour avec succès",

      // Health Records
      healthRecordsDescription: "Suivre et gérer les incidents de santé animale et les traitements",
      addHealthRecord: "Ajouter un dossier de santé",
      healthRecordInformation: "Informations sur le dossier de santé",
      animalTagId: "ID de l'étiquette de l'animal",
      healthIssue: "Problème de santé",
      symptoms: "Symptômes",
      diagnosis: "Diagnostic",
      treatment: "Traitement",
      veterinarian: "Vétérinaire",
      treatmentDate: "Date du traitement",
      followUpDate: "Date de suivi",
      severity: "Gravité",
      cost: "Coût",
      resolved: "Résolu",
      pending: "En attente",
      critical: "Critique",
      moderate: "Modéré",
      mild: "Léger",

      // Vaccinations
      vaccinationsDescription: "Gérer les calendriers et les dossiers de vaccination",
      addVaccination: "Ajouter une vaccination",
      vaccinationInformation: "Informations sur la vaccination",
      vaccineName: "Nom du vaccin",
      manufacturer: "Fabricant",
      batchNumber: "Numéro de lot",
      expiryDate: "Date d'expiration",
      administeredBy: "Administré par",
      nextDueDate: "Prochaine date d'échéance",
      vaccinationType: "Type de vaccination",
      dosage: "Dosage",
      administrationRoute: "Voie d'administration",
      sideEffects: "Effets secondaires",

      // Breeding
      breedingDescription: "Suivre les activités de reproduction et les dossiers de fertilité",
      addBreedingRecord: "Ajouter un dossier de reproduction",
      breedingInformation: "Informations sur la reproduction",
      sireTagId: "ID de l'étiquette du père",
      damTagId: "ID de l'étiquette de la mère",
      breedingDate: "Date de reproduction",
      breedingMethod: "Méthode de reproduction",
      expectedDelivery: "Date de livraison prévue",
      actualDelivery: "Date de livraison réelle",
      numberOfOffspring: "Nombre de descendants",
      breedingNotes: "Notes sur la reproduction",
      naturalMating: "Accouplement naturel",
      artificialInsemination: "Insémination artificielle",
      successful: "Réussi",
      failed: "Échoué",
      inProgress: "En cours",

      // Maintenance
      maintenanceDescription: "Planifier et suivre les activités de maintenance de routine",
      addMaintenanceRecord: "Ajouter un dossier de maintenance",
      maintenanceInformation: "Informations sur la maintenance",
      maintenanceType: "Type de maintenance",
      equipmentId: "ID de l'équipement",
      maintenanceDate: "Date de maintenance",
      performedBy: "Effectué par",
      description: "Description",
      partsUsed: "Pièces utilisées",
      laborHours: "Heures de travail",
      totalCost: "Coût total",
      nextMaintenanceDate: "Prochaine date de maintenance",
      equipmentMaintenance: "Maintenance de l'équipement",
      facilityMaintenance: "Maintenance des installations",
      fencingRepair: "Réparation de clôtures",
      feedingSystemMaintenance: "Maintenance du système d'alimentation",

      // Incidents
      incidentsDescription: "Enregistrer et suivre les incidents et les urgences de la ferme",
      addIncident: "Ajouter un incident",
      incidentInformation: "Informations sur l'incident",
      incidentType: "Type d'incident",
      incidentDate: "Date de l'incident",
      reportedBy: "Signalé par",
      affectedAnimals: "Animaux touchés",
      incidentDescription: "Description de l'incident",
      actionsTaken: "Mesures prises",
      preventiveMeasures: "Mesures préventives",
      incidentStatus: "Statut de l'incident",
      injury: "Blessure",
      illness: "Maladie",
      equipment: "Équipement",
      security: "Sécurité",
      weather: "Météo",
      other: "Autre",

      // Common
      save: "Enregistrer",
      saving: "Enregistrement...",
      edit: "Modifier",
      delete: "Supprimer",
      view: "Afficher",
      backTo: "Retour à",
      required: "Obligatoire",
      optional: "Optionnel",
      selectOption: "Sélectionner une option",
      searchRecords: "Rechercher des enregistrements...",
      filterBy: "Filtrer par",
      sortBy: "Trier par",
      dateRange: "Plage de dates",
      allTypes: "Tous les types",
      allStatuses: "Tous les statuts",
      recordAdded: "Enregistrement ajouté avec succès",
      recordUpdated: "Enregistrement mis à jour avec succès",
      recordDeleted: "Enregistrement supprimé avec succès",
    },
  },
}

export type LanguageCode = keyof typeof languages
export type TranslationKey = keyof typeof languages.en.translations | `Sidebar.${keyof typeof languages.en.translations.Sidebar}`;
